name: build

on: [push, pull_request]

jobs:
  build:
    name: Build and test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-2019, ubuntu-16.04]
    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global core.autocrlf input

      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Log versions
        run: |
          node -v
          npm -v

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup
        run: npm install

      - name: Build
        run: |
          npm run build:dll
          npm run build
